courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail,
        name='text'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail,
        name='quiz'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create,
        name='create_quiz'),
    url(r'(?P<course_pk>\d+)/edit_quiz/(?P<quiz_pk>\d+)/$', views.quiz_edit,
        name='edit_quiz'),
    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$',
        views.create_question, name='create_question'),
    url(r'(?P<quiz_pk>\d+)/edit_question/(?P<question_pk>\d+)/$', views.edit_question,
        name='edit_question'),
    url(r'(?P<question_pk>\d+)/edit_answer/(?P<answer_pk>\d+)/$',
        views.answer_form, name='edit_answer'),
    url(r'(?P<question_pk>\d+)/create_answer/$',
        views.answer_form, name='create_answer'),
    url(r'by/(?P<teacher>[-\w]+)/$', views.courses_by_teacher, name='by_teacher'),
    url(r'search/$', views.search, name='search'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^suggest/$', views.suggestion_view, name='suggestion'),
    url(r'^$', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.core.urlresolvers import reverse
from django.db import models
import math
from django.contrib.auth.models import User

STATUS_CHOICES = (
    ('i', 'In Progress'),
    ('r', 'In Review'),
    ('p', 'Published'),
)


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_live = models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='i')

    def __str__(self):
        return self.title

    def time_to_complete(self):
        from courses.templatetags.course_extras import time_estimate
        return '{} min.'.format(time_estimate(len(self.description.split())))


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    
    class Meta:
        abstract = True
        ordering = ['order',]
    
    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')
    
    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
                'course_pk': self.course_id,
                'step_pk': self.id
            })


class Quiz(Step):
    total_questions = models.IntegerField(default=4)
    times_taken = models.IntegerField(default=0, editable=False)
    
    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse('courses:quiz', kwargs={
                'course_pk': self.course_id,
                'step_pk': self.id
            })

    def number_correct_needed(self):
        return '{}/{}'.format(math.ceil(self.total_questions * 0.7), self.total_questions)

class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    prompt = models.TextField()
    
    class Meta:
        ordering = ['order',]
        
    def get_absolute_url(self):
        return self.quiz.get_absolute_url()
    
    def __str__(self):
        return self.prompt

class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['order',]
        
    def __str__(self):
        return self.text

courses/forms.py
from django import forms

from . import models


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'order',
            'total_questions',
        ]



class QuestionForm(forms.ModelForm):
    class Media:
        css = {'all': ('courses/css/order.css',)}
        js = (
            'courses/js/vendor/jquery.fn.sortable.min.js',
            'courses/js/order.js'
        )


class TrueFalseQuestionForm(QuestionForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = ['order', 'prompt']


class MultipleChoiceQuestionForm(QuestionForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            'order',
            'prompt',
            'shuffle_answers'
        ]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct'
        ]


AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form=AnswerForm,
    extra=2,
)


AnswerInlineFormSet = forms.inlineformset_factory(
    models.Question,
    models.Answer,
    extra=2,
    fields=('order', 'text', 'correct'),
    formset=AnswerFormSet,
    min_num=1,
)

courses/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render

from . import forms
from . import models


def course_list(request):
    courses = models.Course.objects.filter(
        status='p'
    ).annotate(
        total_steps=Count('text', distinct=True)+Count('quiz', distinct=True)
    )
    return render(request, 'courses/course_list.html', {
        'courses': courses,
    })


def course_detail(request, pk):
    try:
        course = models.Course.objects.prefetch_related(
            'quiz_set', 'text_set', 'quiz_set__question_set'
        ).get(pk=pk, status='p')
    except models.Course.DoesNotExist:
        raise Http404
    else:
        steps = sorted(chain(
                course.text_set.all(),
                course.quiz_set.all()
            ), key=lambda step: step.order)
    return render(request, 'courses/course_detail.html', {
            'course': course,
            'steps': steps
        })


def text_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Text,
                             course_id=course_pk,
                             pk=step_pk,
                             course__status='p')
    return render(request, 'courses/text_detail.html', {'step': step})


def quiz_detail(request, course_pk, step_pk):
    try:
        step = models.Quiz.objects.select_related(
            'course'
        ).prefetch_related(
            'question_set',
            'question_set__answer_set',
        ).get(
            course_id=course_pk,
            pk=step_pk,
            course__status='p'
        )
    except models.Quiz.DoesNotExist:
        raise Http404
    else:
        return render(request, 'courses/quiz_detail.html', {'step': step})


@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk, course__status='p')
    form = forms.QuizForm()
    
    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Quiz added!")
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form, 'course': course})


@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz,
                             pk=quiz_pk,
                             course_id=course_pk,
                             course__status='p')
    form = forms.QuizForm(instance=quiz)
    
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form, 'course': quiz.course})


@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    if question_type == 'tf':
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm
    
    form = form_class()
    answer_forms = forms.AnswerInlineFormSet(
        queryset=models.Answer.objects.none()
    )
    
    if request.method == 'POST':
        form = form_class(request.POST)
        answer_forms = forms.AnswerInlineFormSet(
            request.POST,
            queryset=models.Answer.objects.none()
        )
        
        if form.is_valid() and answer_forms.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Added question")
            return HttpResponseRedirect(quiz.get_absolute_url())
    
    return render(request, 'courses/question_form.html', {
            'quiz': quiz,
            'form': form,
            'formset': answer_forms
    })


@login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question,
                                 pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForm
        question = question.truefalsequestion
    else:
        form_class = forms.MultipleChoiceQuestionForm
        question = question.multiplechoicequestion
    form = form_class(instance=question)
    answer_forms = forms.AnswerInlineFormSet(
        queryset=form.instance.answer_set.all()
    )
    
    if request.method == 'POST':
        form = form_class(request.POST, instance=question)
        answer_forms = forms.AnswerInlineFormSet(
            request.POST,
            queryset=form.instance.answer_set.all()
        )
        if form.is_valid() and answer_forms.is_valid():
            form.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            for answer in answer_forms.deleted_objects:
                answer.delete()
            messages.success(request, "Updated question")
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {
            'form': form,
            'quiz': question.quiz,
            'formset': answer_forms
    })


@login_required
def answer_form(request, question_pk, answer_pk=None):
    question = get_object_or_404(models.Question, pk=question_pk)
    formset = forms.AnswerFormSet(queryset=question.answer_set.all())
    
    if request.method == 'POST':
        formset = forms.AnswerFormSet(request.POST,
                                      queryset=question.answer_set.all())
        
        if formset.is_valid():
            answers = formset.save(commit=False)
            
            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Added answers")
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/answer_form.html', {
            'formset': formset,
            'question': question
    })


def courses_by_teacher(request, teacher):
    courses = models.Course.objects.filter(teacher__username=teacher,
                                           status='p')
    return render(request, 'courses/course_list.html', {'courses': courses})


def search(request):
    term = request.GET.get('q')
    courses = models.Course.objects.filter(
        Q(title__icontains=term)|Q(description__icontains=term),
        status='p'
    )
    return render(request, 'courses/course_list.html', {'courses': courses})

courses/templates/courses/answer_form.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ question|default:"New answer" }} | {{ question.quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=question.quiz.course.pk %}">{{ question.quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz' course_pk=question.quiz.course.pk step_pk=question.quiz.pk %}">{{ question.quiz.title }}</a></li>
    <li>{{ question.prompt }}</li>
{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row columns">
        <h1>Answers</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <section>
                {{ formset }}
            </section>
            <input type="submit" class="button" value="Save">
        </form>
    </div>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <article>
            <h1 class="">{{ course.title }}</h1>

            <div class="callout secondary">
                {{ course.description|markdown_to_html }}
            </div>

            <dl>
                {% for step in steps %}
                    <dt>
                        <a href="{{ step.get_absolute_url }}">{{ step.title }}</a>
                    </dt>
                    <dd>{{ step.description|markdown_to_html }}</dd>
                    {% if step.question_set.all %}
                        <dt>Total Questions</dt>
                        <dd>{{ step.question_set.count }}</dd>
                    {% endif %}
                {% endfor %}
            </dl>
        </article>
        {% if user.is_authenticated %}
        <hr>
        <a href="{% url 'courses:create_quiz' course_pk=course.id %}" class="button">New Quiz</a>
        {% endif %}
    </div>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "courses/layout.html" %}

{% block title %}All{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row">
        {%  for course in courses %}
            <div class="small-6 columns">
                <div class="callout">
                    <h5><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></h5>
                    <div class="card-copy">
                        {{ course.description }}
                        {% if course.total_steps %}
                            <p><strong>Steps:</strong> {{ course.total_steps }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>

            {% if forloop.counter|divisibleby:"2" %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %} 
    <li><a href="{% url 'courses:detail' pk=course.id %}">{{ course.title }}</a></li>
{% endfor %}

courses/templates/courses/layout.html
{% extends "layout.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'courses:list' %}">Courses</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

courses/templates/courses/question_form.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ form.instance.prompt|default:"New question" }} | {{ quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=quiz.course.pk %}">{{ quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz' course_pk=quiz.course.pk step_pk=quiz.pk %}">{{ quiz.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.prompt|default:"Make a new question" }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        
        {{ formset.management_form }}
        
        <table role="grid" class="stack hover" style="width: 100%">
            <thead>
                <tr>
                    <th scope="col" class="text-center" style="width: 10%">Order</th>
                    <th scope="col" class="text-center">Text</th>
                    <th scope="col" class="text-center" style="width: 10%">Correct?</th>
                    <th scope="col" class="text-center" style="width: 10%">Delete?</th>
                </tr>
            </thead>
            <tbody class="order">
                {% for form in formset %}
                    <tr class="answer-form {% if form.instance.pk %}item{% else %}new{% endif %}">
                        <td>{{ form.id }}{{ form.order }}</td>
                        <td>{{ form.text }}</td>
                        <td class="text-center">{{ form.correct }}</td>
                        {% if form.instance.pk %}
                            <td class="text-center">{{ form.DELETE }}</td>
                        {% else %}
                            <td class="text-center"></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <input type="submit" class="button" value="Save">
    </form>
</div>
{% endblock %}

{% block css %}
    {{ form.media.css }}
{% endblock %}

{% block javascript %}
    {% load static from staticfiles %}
    {{ form.media.js }}
    <script src="{% static 'js/vendor/jquery.formset.js' %}"></script>
    <script>
        $('.answer-form').formset({
            addText: 'add answer',
            deleteText: 'remove'
        });
    </script>
{% endblock %}

courses/templates/courses/quiz_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <ul class="no-bullet">
                {% for question in step.question_set.all %}
                <li>
                    <h2>{{ question.prompt }}</h2>
                    {% for answer in question.answer_set.all %}
                        <div class="callout {% if answer.correct %}success{% endif %}">{{ answer.text }}</div>
                    {% endfor %}
                    {% if user.is_authenticated %}
                        <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}" class="button">Edit</a>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </article>
        {% if user.is_authenticated %}
        <hr>
        <a href="{% url 'courses:edit_quiz' course_pk=step.course.pk quiz_pk=step.pk %}" class="button">Edit</a>
        <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type="mc" %}" class="button">New Multiple Choice</a>
        <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type="tf" %}" class="button">New True/False</a>
        {% endif %}
    </div>
{% endblock %}

courses/templates/courses/quiz_form.html
{% extends "courses/layout.html" %}

{% block title %}{{ form.instance.title|default:"New Quiz" }} | {{ course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
<div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.title|default:"Make a new quiz" }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
</div>
{% endblock %}

courses/templates/courses/quiz_step.html
{% extends "courses/layout.html" %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <ul class="no-bullet">
            {% for question in step.question_set.all %}
                <li>
                    <h3 class="subheader">{{ question.prompt }}</h3>
                    {% for answer in question.answer_set.all %}
                        <div class="callout {% if answer.correct and user.is_superuser%}success{% endif %}">{{ answer.text }}</div>
                    {% endfor %}
                    {% if user.is_superuser %}
                        <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}" class="tiny button">Edit Question</a>
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        {% if user.is_superuser %}
            <hr>
            <div class="button-group">
                <a href="{% url 'courses:edit_quiz' course_pk=step.course_id quiz_pk=step.pk %}" class="small button">Edit Quiz</a>
                <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='mc' %}" class="small button">Add Multiple Choice</a>
                <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='tf' %}" class="small button">Add True/False</a>
            </div>
        {% endif %}
        </article>
    </div>
{% endblock %}

courses/templates/courses/text_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}

courses/templates/courses/text_step.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}